### ISSUE TITLE
Error code: C86044CD

### ISSUE THREAD

**Issue by theCoderCat** [smealum/sploit_installer#2]
I tried to install OOT3DHAX today, everything went smoothy until

```
Downloading payload...
Installing payload...
Looks like something went wrong. :(
```

```
Current status:
  Failed to install payload
  Error code :  C86044CD
```

My system firmware is OLD 9.5.0.23U
Install on 3rd save slot

**Comment by yellows8** [comment]
You have to delete all of your savefiles.

**Comment by theCoderCat** [comment]
Thanks, it worked :+1:

**Comment by geekpersonman** [comment]
All of them?

**Comment by DanteJaggerjack** [comment]
Hi, 
I have a problem when trying to install oothax

Downloading payload...
Installing payload...
Looks like something went wrong. :(
Current status:
  Failed to install payload
  Error code :  D8A0A01E
My system firmware is OLD 11.0.0-33U

in any of the slots same thing happens, help Please!!

**Comment by yellows8** [comment]
That's just network fail, retry.
